//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergonSoftware.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergonSoftware.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to internal error!.
        /// </summary>
        internal static string DisconnectInternalError {
            get {
                return ResourceManager.GetString("DisconnectInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to socket closed!.
        /// </summary>
        internal static string DisconnectSocketClosed {
            get {
                return ResourceManager.GetString("DisconnectSocketClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to timeout!.
        /// </summary>
        internal static string DisconnectTimeout {
            get {
                return ResourceManager.GetString("DisconnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while creating socket!.
        /// </summary>
        internal static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP server is already running!.
        /// </summary>
        internal static string ErrorHttpServerAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorHttpServerAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while sending session data!.
        /// </summary>
        internal static string ErrorSendingSessionData {
            get {
                return ResourceManager.GetString("ErrorSendingSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL handshake failed!.
        /// </summary>
        internal static string ErrorSSLHandshakeFailed {
            get {
                return ResourceManager.GetString("ErrorSSLHandshakeFailed", resourceCulture);
            }
        }
    }
}
