//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergonSoftware.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergonSoftware.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to internal error!.
        /// </summary>
        internal static string DisconnectInternalError {
            get {
                return ResourceManager.GetString("DisconnectInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to socket closed!.
        /// </summary>
        internal static string DisconnectSocketClosed {
            get {
                return ResourceManager.GetString("DisconnectSocketClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect due to timeout!.
        /// </summary>
        internal static string DisconnectTimeout {
            get {
                return ResourceManager.GetString("DisconnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create handler for message type: {0}.
        /// </summary>
        internal static string ErrorCreatingMessageHandler {
            get {
                return ResourceManager.GetString("ErrorCreatingMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while creating socket!.
        /// </summary>
        internal static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while deserializing content!.
        /// </summary>
        internal static string ErrorDeserializingNetworkPacketContent {
            get {
                return ResourceManager.GetString("ErrorDeserializingNetworkPacketContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while handling message!.
        /// </summary>
        internal static string ErrorHandlingMessage {
            get {
                return ResourceManager.GetString("ErrorHandlingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP server is already running!.
        /// </summary>
        internal static string ErrorHttpServerAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorHttpServerAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login: {0}.
        /// </summary>
        internal static string ErrorInvalidLogin {
            get {
                return ResourceManager.GetString("ErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login account: {0}, expected: {1}.
        /// </summary>
        internal static string ErrorInvalidLoginAccount {
            get {
                return ResourceManager.GetString("ErrorInvalidLoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network packet marker found!.
        /// </summary>
        internal static string ErrorInvalidNetworkPacketMarker {
            get {
                return ResourceManager.GetString("ErrorInvalidNetworkPacketMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network packet terminator found!.
        /// </summary>
        internal static string ErrorInvalidNetworkPacketTerminator {
            get {
                return ResourceManager.GetString("ErrorInvalidNetworkPacketTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message handler is already running!.
        /// </summary>
        internal static string ErrorMessageHandlerAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorMessageHandlerAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message processor already running!.
        /// </summary>
        internal static string ErrorMessageProcessorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorMessageProcessorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while parsing messages!.
        /// </summary>
        internal static string ErrorParsingMessages {
            get {
                return ResourceManager.GetString("ErrorParsingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while parsing network packet!.
        /// </summary>
        internal static string ErrorParsingNetworkPacket {
            get {
                return ResourceManager.GetString("ErrorParsingNetworkPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while sending message!.
        /// </summary>
        internal static string ErrorSendingMessage {
            get {
                return ResourceManager.GetString("ErrorSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is already authenticated!.
        /// </summary>
        internal static string ErrorSessionAlreadyAuthenticated {
            get {
                return ResourceManager.GetString("ErrorSessionAlreadyAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is not authenticated!.
        /// </summary>
        internal static string ErrorSessionNotAuthenticated {
            get {
                return ResourceManager.GetString("ErrorSessionNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported message type for construction: {0}.
        /// </summary>
        internal static string ErrorUnsupportedMessage {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported message formatter type for construction: {0}.
        /// </summary>
        internal static string ErrorUnsupportedMessageFormatter {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMessageFormatter", resourceCulture);
            }
        }
    }
}
