//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergonSoftware.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergonSoftware.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete network packet!.
        /// </summary>
        public static string ErrorIncompleteNetworkPacket {
            get {
                return ResourceManager.GetString("ErrorIncompleteNetworkPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login: {0}.
        /// </summary>
        public static string ErrorInvalidLogin {
            get {
                return ResourceManager.GetString("ErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login account: {0}, expected: {1}.
        /// </summary>
        public static string ErrorInvalidLoginAccount {
            get {
                return ResourceManager.GetString("ErrorInvalidLoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network packet marker found!.
        /// </summary>
        public static string ErrorInvalidNetworkPacketMarker {
            get {
                return ResourceManager.GetString("ErrorInvalidNetworkPacketMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network packet terminator found!.
        /// </summary>
        public static string ErrorInvalidNetworkPacketTerminator {
            get {
                return ResourceManager.GetString("ErrorInvalidNetworkPacketTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message handler is already running!.
        /// </summary>
        public static string ErrorMessageHandlerAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorMessageHandlerAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message processor already running!.
        /// </summary>
        public static string ErrorMessageProcessorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorMessageProcessorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while parsing network packet!.
        /// </summary>
        public static string ErrorParsingNetworkPacket {
            get {
                return ResourceManager.GetString("ErrorParsingNetworkPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while sending message!.
        /// </summary>
        public static string ErrorSendingMessage {
            get {
                return ResourceManager.GetString("ErrorSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is already authenticated!.
        /// </summary>
        public static string ErrorSessionAlreadyAuthenticated {
            get {
                return ResourceManager.GetString("ErrorSessionAlreadyAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is not authenticated!.
        /// </summary>
        public static string ErrorSessionNotAuthenticated {
            get {
                return ResourceManager.GetString("ErrorSessionNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported message type for construction: {0}.
        /// </summary>
        public static string ErrorUnsupportedMessage {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported message formatter type for construction: {0}.
        /// </summary>
        public static string ErrorUnsupportedMessageFormatter {
            get {
                return ResourceManager.GetString("ErrorUnsupportedMessageFormatter", resourceCulture);
            }
        }
    }
}
